name: "Frogbot Repo Scan"

on:
  push: # Triggers scan-repo flow for every push to the specified branches
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: read           # for detecting the Github Actions environment
  id-token: write         # for creating OIDC tokens for signing
  pull-requests: write    # for writing to PRs
  contents: write         # for creating fixing pull requests and pushing changes
  security-events: write  # for uploading SARIF results to GitHub Code Scanning

jobs:
  scan-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: jfrog/frogbot@v2
        # [Mandatory if using OIDC authentication protocol instead of JF_ACCESS_TOKEN]
        # Insert to oidc-provider-name the 'Provider Name' defined in the OIDC integration configured in the JPD
        with:
           oidc-provider-name: setup-jfrog-cli
           oidc-audience: jfrog-github
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
